import json
from pathlib import Path

pairs = """
apple|jabłko
banana|banan
orange|pomarańcza
pear|gruszka
peach|brzoskwinia
plum|śliwka
strawberry|truskawka
raspberry|malina
blueberry|borówka
watermelon|arbuz
melon|melon
cherry|wiśnia
grape|winogrono
lemon|cytryna
lime|limonka
pineapple|ananas
mango|mango
apricot|morela
fig|figa
date|daktyl
coconut|kokos
kiwi|kiwi
pomegranate|granat
papaya|papaja
cranberry|żurawina
blackberry|jeżyna
currant|porzeczka
olive|oliwka
avocado|awokado
tomato|pomidor
cucumber|ogórek
carrot|marchew
potato|ziemniak
onion|cebula
garlic|czosnek
cabbage|kapusta
lettuce|sałata
spinach|szpinak
broccoli|brokuł
cauliflower|kalafior
pepper|papryka
pumpkin|dynia
zucchini|cukinia
beetroot|burak
radish|rzodkiewka
parsley|pietruszka
celery|seler
leek|por
eggplant|bakłażan
bean|fasola
pea|groszek
corn|kukurydza
lentil|soczewica
chickpea|ciecierzyca
rice|ryż
wheat|pszenica
oat|owies
barley|jęczmień
rye|żyto
bread|chleb
butter|masło
cheese|ser
yogurt|jogurt
milk|mleko
cream|śmietana
egg|jajko
chicken|kurczak
beef|wołowina
pork|wieprzowina
lamb|jagnięcina
ham|szynka
sausage|kiełbasa
fish|ryba
salmon|łosoś
trout|pstrąg
herring|śledź
shrimp|krewetka
crab|krab
lobster|homar
mussel|małża
oyster|ostryga
breadroll|bułka
cake|ciasto
cookie|ciastko
pie|tarta
sugar|cukier
salt|sól
peppercorn|pieprz
spice|przyprawa
herb|zioło
basil|bazylia
oregano|oregano
rosemary|rozmaryn
thyme|tymianek
mint|mięta
cinnamon|cynamon
vanilla|wanilia
honey|miód
jam|dżem
soup|zupa
salad|sałatka
breakfast|śniadanie
lunch|lunch
dinner|obiad
snack|przekąska
dessert|deser
water|woda
juice|sok
tea|herbata
coffee|kawa
beer|piwo
wine|wino
soda|napój gazowany
animal|zwierzę
dog|pies
cat|kot
horse|koń
cow|krowa
pig|świnia
sheep|owca
goat|koza
rabbit|królik
fox|lis
wolf|wilk
bear|niedźwiedź
lion|lew
tiger|tygrys
monkey|małpa
elephant|słoń
giraffe|żyrafa
zebra|zebra
kangaroo|kangur
koala|koala
panda|panda
camel|wielbłąd
squirrel|wiewiórka
mouse|mysz
rat|szczur
hedgehog|jeż
badger|borsuk
beaver|bóbr
otter|wydra
deer|jeleń
elk|łoś
boar|dzik
bird|ptak
eagle|orzeł
hawk|jastrząb
owl|sowa
sparrow|wróbel
pigeon|gołąb
duck|kaczka
goose|gęś
swan|łabędź
stork|bocian
peacock|paw
rooster|kogut
hen|kura
chick|pisklę
butterfly|motyl
bee|pszczoła
wasp|osa
ant|mrówka
beetle|chrząszcz
ladybug|biedronka
fly|mucha
mosquito|komar
spider|pająk
worm|robak
forest|las
tree|drzewo
bush|krzew
flower|kwiat
leaf|liść
root|korzeń
branch|gałąź
trunk|pień
bark|kora
seed|nasiono
soil|gleba
stone|kamień
rock|skała
mountain|góra
hill|wzgórze
valley|dolina
plain|równina
river|rzeka
stream|strumień
lake|jezioro
sea|morze
ocean|ocean
waterfall|wodospad
cave|jaskinia
desert|pustynia
beach|plaża
coast|wybrzeże
island|wyspa
peninsula|półwysep
rain|deszcz
snow|śnieg
hail|grad
fog|mgła
cloud|chmura
sky|niebo
sun|słońce
moon|księżyc
star|gwiazda
wind|wiatr
storm|burza
thunder|grzmot
lightning|błyskawica
rainbow|tęcza
climate|klimat
weather|pogoda
temperature|temperatura
season|pora roku
spring|wiosna
summer|lato
autumn|jesień
winter|zima
north|północ
south|południe
east|wschód
west|zachód
compass|kompas
map|mapa
city|miasto
town|miasteczko
village|wieś
street|ulica
road|droga
square|plac
bridge|most
park|park
garden|ogród
playground|plac zabaw
school|szkoła
hospital|szpital
library|biblioteka
museum|muzeum
theater|teatr
cinema|kino
restaurant|restauracja
cafe|kawiarnia
shop|sklep
market|targ
station|dworzec
airport|lotnisko
harbor|port
building|budynek
house|dom
apartment|mieszkanie
room|pokój
kitchen|kuchnia
bathroom|łazienka
bedroom|sypialnia
livingroom|salon
attic|strych
basement|piwnica
roof|dach
wall|ściana
door|drzwi
window|okno
floor|podłoga
ceiling|sufit
stairs|schody
elevator|winda
balcony|balkon
garage|garaż
furniture|meble
chair|krzesło
armchair|fotel
sofa|kanapa
table|stół
desk|biurko
bed|łóżko
wardrobe|szafa
shelf|półka
cabinet|szafka
lamp|lampa
carpet|dywan
curtain|zasłona
mirror|lustro
clock|zegar
picture|obraz
television|telewizor
computer|komputer
laptop|laptop
keyboard|klawiatura
mouse_device|myszka
monitor|monitor
printer|drukarka
router|router
smartphone|smartfon
tablet|tablet
camera|aparat
headphones|słuchawki
microphone|mikrofon
speaker|głośnik
battery|bateria
charger|ładowarka
cable|kabel
plug|wtyczka
socket|gniazdko
internet|internet
website|strona internetowa
password|hasło
software|oprogramowanie
hardware|sprzęt
update|aktualizacja
backup|kopia zapasowa
cloud|chmura danych
server|serwer
network|sieć
database|baza danych
file|plik
folder|folder
settings|ustawienia
message|wiadomość
notification|powiadomienie
user|użytkownik
account|konto
profile|profil
privacy|prywatność
security|bezpieczeństwo
algorithm|algorytm
robot|robot
machine|maszyna
vehicle|pojazd
car|samochód
bus|autobus
tram|tramwaj
train|pociąg
subway|metro
bicycle|rower
scooter|hulajnoga
motorcycle|motocykl
truck|ciężarówka
ship|statek
boat|łódź
plane|samolot
helicopter|helikopter
rocket|rakieta
passport|paszport
ticket|bilet
luggage|bagaż
suitcase|walizka
backpack|plecak
hotel|hotel
reservation|rezerwacja
checkin|zameldowanie
checkout|wymeldowanie
tourist|turysta
guide|przewodnik
maple|klon
birch|brzoza
pine|sosna
spruce|świerk
fir|jodła
cedar|cedr
willow|wierzba
poplar|topola
ash|jesion
hazel|leszczyna
elder|bez
chestnut|kasztanowiec
walnut|orzech włoski
acorn|żołądź
mushroom|grzyb
berry|jagoda
heron|czapla
seagull|mewa
shark|rekin
dolphin|delfin
whale|wieloryb
seal|foka
penguin|pingwin
polar_bear|niedźwiedź polarny
reef|rafa
coral|koral
octopus|ośmiornica
jellyfish|meduza
turtle|żółw
seahorse|konik morski
clam|małż
kelp|wodorost
seaweed|glon
algae|alga
barnacle|pąkla
plankton|plankton
harvest|żniwa
farmer|rolnik
tractor|ciągnik
field|pole
grain|zboże
hay|siano
barn|stodoła
stable|stajnia
coop|kurnik
pasture|pastwisko
fence|płot
tool|narzędzie
hammer|młotek
screwdriver|śrubokręt
wrench|klucz
pliers|szczypce
saw|piła
drill|wiertarka
nail|gwóźdź
screw|śruba
bolt|śruba z nakrętką
nut|nakrętka
glove|rękawica
goggles|gogle
helmet|kask
safety|bezpieczeństwo
measure|miarka
level|poziomica
tape|taśma
paint|farba
brush|pędzel
roller|wałek
bucket|wiadro
ladder|drabina
cement|cement
brick|cegła
sand|piasek
gravel|żwir
concrete|beton
steel|stal
wood|drewno
plastic|plastik
glass|szkło
paper|papier
cardboard|tektura
rubber|guma
cotton|bawełna
wool|wełna
silk|jedwab
leather|skóra
fabric|tkanina
thread|nić
needle|igła
scissors|nożyczki
button|guzik
zipper|zamek
sewing|szycie
pattern|wykrój
notebook|notes
pen|długopis
pencil|ołówek
marker|marker
eraser|gumka
sharpener|temperówka
ruler|linijka
calculator|kalkulator
paperclip|spinacz
envelope|koperta
stamp|znaczek
mailbox|skrzynka pocztowa
package|paczka
parcel|przesyłka
postman|listonosz
letter|list
calendar|kalendarz
schedule|grafik
meeting|spotkanie
appointment|wizyta
deadline|termin
project|projekt
task|zadanie
note|notatka
idea|pomysł
plan|plan
strategy|strategia
goal|cel
success|sukces
failure|porażka
progress|postęp
improvement|poprawa
innovation|innowacja
motivation|motywacja
focus|koncentracja
team|zespół
leader|lider
manager|menedżer
employee|pracownik
colleague|kolega z pracy
customer|klient
partner|partner
contract|kontrakt
invoice|faktura
budget|budżet
finance|finanse
investment|inwestycja
profit|zysk
loss|strata
market|rynek
supply|podaż
demand|popyt
price|cena
value|wartość
data|dane
analysis|analiza
report|raport
risk|ryzyko
policy|polityka
regulation|regulacja
law|prawo
justice|sprawiedliwość
court|sąd
judge|sędzia
lawyer|prawnik
police|policja
firefighter|strażak
doctor|lekarz
nurse|pielęgniarka
scientist|naukowiec
engineer|inżynier
architect|architekt
artist|artysta
musician|muzyk
writer|pisarz
journalist|dziennikarz
photographer|fotograf
teacher|nauczyciel
student|student
athlete|sportowiec
coach|trener
chef|szef kuchni
waiter|kelner
barista|barista
cashier|kasjer
mechanic|mechanik
electrician|elektryk
plumber|hydraulik
carpenter|stolarz
smith|kowal
tailor|krawiec
hairdresser|fryzjer
pilot|pilot
sailor|żeglarz
soldier|żołnierz
translator|tłumacz
psychologist|psycholog
therapist|terapeuta
vet|weterynarz
librarian|bibliotekarz
actor|aktor
actress|aktorka
singer|piosenkarz
composer|kompozytor
dancer|tancerz
sculptor|rzeźbiarz
painter|malarz
poet|poeta
accountant|księgowy
consultant|konsultant
analyst|analityk
researcher|badacz
entrepreneur|przedsiębiorca
founder|założyciel
trader|handlarz
broker|makler
miner|górnik
explorer|odkrywca
astronaut|astronauta
mayor|burmistrz
governor|gubernator
president|prezydent
minister|minister
ambassador|ambasador
diplomat|dyplomata
citizen|obywatel
neighbor|sąsiad
friend|przyjaciel
family|rodzina
parent|rodzic
mother|matka
father|ojciec
sister|siostra
brother|brat
child|dziecko
baby|niemowlę
teenager|nastolatek
adult|dorosły
senior|senior
marriage|małżeństwo
wedding|ślub
birthday|urodziny
holiday|święto
festival|festiwal
celebration|uroczystość
tradition|tradycja
culture|kultura
history|historia
future|przyszłość
present|teraźniejszość
past|przeszłość
memory|pamięć
story|opowieść
legend|legenda
hero|bohater
journey|podróż
adventure|przygoda
challenge|wyzwanie
victory|zwycięstwo
defeat|porażka
freedom|wolność
equality|równość
respect|szacunek
trust|zaufanie
loyalty|lojalność
courage|odwaga
patience|cierpliwość
kindness|życzliwość
empathy|empatia
honesty|uczciwość
wisdom|mądrość
knowledge|wiedza
learning|nauka
exam|egzamin
grade|ocena
diploma|dyplom
scholarship|stypendium
laboratory|laboratorium
experiment|eksperyment
result|wynik
conclusion|wniosek
presentation|prezentacja
conference|konferencja
seminar|seminarium
workshop|warsztat
community|społeczność
support|wsparcie
volunteer|wolontariusz
charity|organizacja charytatywna
donation|darowizna
movement|ruch
initiative|inicjatywa
vision|wizja
mission|misja
impact|wpływ
environment|środowisko
ecosystem|ekosystem
pollution|zanieczyszczenie
recycling|recykling
energy|energia
solar|słoneczny
windmill|wiatrak
battery_pack|magazyn energii
transport|transport
logistics|logistyka
warehouse|magazyn
delivery|dostawa
inventory|zapasy
storage|składowanie
tracking|śledzenie
customer_service|obsługa klienta
helpdesk|pomoc techniczna
feedback|opinie
survey|ankieta
rating|ocena
review|recenzja
benchmark|benchmark
standard|standard
quality|jakość
warranty|gwarancja
return|zwrot
exchange|wymiana
repair|naprawa
maintenance|utrzymanie
inspection|inspekcja
procedure|procedura
manual|podręcznik
prototype|prototyp
version|wersja
roadmap|plan działania
milestone|kamień milowy
sprint|sprint
backlog|lista zadań
issue|problem
bug|błąd
fix|poprawka
patch|łatka
commit|commit
merge|scalenie
branch|gałąź
repository|repozytorium
deploy|wdrożenie
monitoring|monitoring
alert|alert
incident|incydent
uptime|czas działania
latency|opóźnienie
optimization|optymalizacja
scalability|skalowalność
performance|wydajność
load|obciążenie
capacity|pojemność
usage|użycie
quota|limit
"""

data = []
for line in pairs.strip().split("\n"):
  if not line.strip() or "|" not in line:
    continue
  en, pl = line.split("|", 1)
  data.append({"en": en.strip(), "pl": pl.strip()})

output_path = Path("bow_client/assets/words.json")
output_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Wrote {len(data)} entries to {output_path}")
